Feature/left menu
ATech-Solution/vsf-capybara pull request #2
Opened 2021-03-05 07:51 UTC by EdwardAJ

### **Task**

-  https://trello.com/c/TgSD4rsW/17-browse-page-left-menu

### **Description**
This PR includes:
- Buefy, Vue-property-decorator, Vue-class-component installation
- Add some webpack configurations
- Gilroy font-family installation
- Basic sidebar. Sidebar will change the menu item to active based on current page URL. For now, it's still in **_TODO_**.

**The sidebar will block the browse page for now**. In the future, the sidebar will be placed in Default.vue under layouts directory.

### **Screenshot**
![Screenshot from 2021-03-05 14-45-55](https://user-images.githubusercontent.com/20357281/110084056-14bd2680-7dc2-11eb-93dd-526b9fea0a7c.png)

2021-03-05 16:16 UTC, astaphobia commented on components/organisms/o-sidebar.vue
> +  items: Items = {
Just suggestion, would be better to use asset for this, just load from asset the list instead of hard code like this. Isn't it ?

2021-03-05 16:24 UTC, astaphobia requested changes
Leggit 🔥
Just need to ignore some file such as ` yarn-error.log`

2021-03-08 06:17 UTC, EdwardAJ commented on components/organisms/o-sidebar.vue
> +  items: Items = {
Something like .env? @astaphobia

2021-03-08 14:16 UTC, astaphobia commented on components/atoms/a-menu-label.vue
> +<template>
Are these component used ? 
If not, do we push it also or not ?

2021-03-09 05:49 UTC, EdwardAJ commented on components/atoms/a-menu-label.vue
> +<template>
Yes. It is used in `o-sidebar.vue`. Will be pushed.

2021-03-09 06:38 UTC, astaphobia approved these changes
I'm not sure if `Buefy` will good and not has conflict with other functionality, let merge first and see.

2021-03-09 06:39 UTC, merged